application: tech-trends
version: version-0-0
runtime: python27
api_version: 1
threadsafe: false

libraries:
- name: PIL
  version: latest
- name: django
  version: 1.3


builtins:
- remote_api: on
 
handlers:

- url: /favicon\.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon\.ico

- url: /apple-touch-icon-114x114-precomposed\.png
  static_files: static/images/apple-touch-icon-72x72-precomposed.png
  upload: static/images/apple-touch-icon-72x72-precomposed\.png

- url: /apple-touch-icon-72x72-precomposed\.png
  static_files: static/images/apple-touch-icon-72x72-precomposed.png
  upload: static/images/apple-touch-icon-72x72-precomposed\.png

- url: /apple-touch-icon-57x57-precomposed\.png
  static_files: static/images/apple-touch-icon-72x72-precomposed.png
  upload: static/images/apple-touch-icon-72x72-precomposed\.png


- url: /stylesheets
  static_dir: stylesheets

- url: /javascript
  static_dir: javascript

- url: /images
  static_dir: images

- url: /admin/.*
  script: main.py
  login: admin

- url: /westoefarm.co.uk/stylesheets
  static_dir: westoefarm.co.uk/stylesheets

- url: /westoefarm.co.uk/images
  static_dir: westoefarm.co.uk/images

- url: /westoefarm.co.uk/javascript
  static_dir: /westoefarm.co.uk/javascript

- url: /westoefarm.co.uk/.*
  script: main.py
  login: required

- url: .*
  script: main.py
